// 生成控制流关键字
// export function spawnKeywordControlFlow() {
//     return ['IF', 'ELSE', 'ENDIF', 'ELSEIF', 'SIF', 'FOR', 'NEXT', 'WHILE', 'GOTO', 'RETURN '];
// }

// export function spawnKeywordOther() {
//     return ['CALL', 'RESULT'];
// }

// export function spawnKeywordShort() {
//     return ['@', '#'];
// }
// console.log(`{label:'${a[b]}',detail:{'zh-CN':{short:'输出',long:'输出-'}}},`);

// console.log(spawnKeywordIO());


// export Keyword

// 仅做为生成关键字
class Keyword {
    constructor() {
        this, Table = [
            { label: 'PRINT', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-跟随SetColor' } } },
            { label: 'PRINTL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-跟随SetColor-换行' } } },
            { label: 'PRINTW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-跟随SetColor-换行后等待' } } },
            { label: 'PRINTK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-跟随ForceKana' } } },
            { label: 'PRINTKL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-跟随ForceKana-换行' } } },
            { label: 'PRINTKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-忽略SetColor' } } },
            { label: 'PRINTDL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-忽略SetColor-换行' } } },
            { label: 'PRINTDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-忽略SetColor-换行后等待' } } },
            { label: 'PRINTLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-左对齐-跟随SetColor' } } },
            { label: 'PRINTLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-左对齐-跟随ForceKana' } } },
            { label: 'PRINTLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-左对齐-忽略SetColor' } } },
            { label: 'PRINTLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-右对齐-跟随SetColor' } } },
            { label: 'PRINTCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-右对齐-跟随ForceKana' } } },
            { label: 'PRINTCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-右对齐-忽略SetColor' } } },
            { label: 'PRINTCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTV', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-跟随SetColor' } } },
            { label: 'PRINTVL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-跟随SetColor-换行' } } },
            { label: 'PRINTVW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-跟随SetColor-换行后等待' } } },
            { label: 'PRINTVK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-跟随ForceKana' } } },
            { label: 'PRINTVKL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-跟随ForceKana-换行' } } },
            { label: 'PRINTVKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTVD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-忽略SetColor' } } },
            { label: 'PRINTVDL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-忽略SetColor-换行' } } },
            { label: 'PRINTVDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-忽略SetColor-换行后等待' } } },
            { label: 'PRINTVLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-左对齐-跟随SetColor' } } },
            { label: 'PRINTVLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTVLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-左对齐-跟随ForceKana' } } },
            { label: 'PRINTVLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTVLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-左对齐-忽略SetColor' } } },
            { label: 'PRINTVLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTVC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-右对齐-跟随SetColor' } } },
            { label: 'PRINTVCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTVCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-右对齐-跟随ForceKana' } } },
            { label: 'PRINTVCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTVCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-右对齐-忽略SetColor' } } },
            { label: 'PRINTVCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-数值表达式-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTS', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-跟随SetColor' } } },
            { label: 'PRINTSL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-跟随SetColor-换行' } } },
            { label: 'PRINTSW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-跟随ForceKana' } } },
            { label: 'PRINTSKL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-跟随ForceKana-换行' } } },
            { label: 'PRINTSKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-忽略SetColor' } } },
            { label: 'PRINTSDL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-忽略SetColor-换行' } } },
            { label: 'PRINTSDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-左对齐-跟随SetColor' } } },
            { label: 'PRINTSLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-左对齐-跟随ForceKana' } } },
            { label: 'PRINTSLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-左对齐-忽略SetColor' } } },
            { label: 'PRINTSLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-右对齐-跟随SetColor' } } },
            { label: 'PRINTSCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-右对齐-跟随ForceKana' } } },
            { label: 'PRINTSCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-右对齐-忽略SetColor' } } },
            { label: 'PRINTSCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-字符串表达式-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTFORM', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-跟随SetColor' } } },
            { label: 'PRINTFORML', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-跟随SetColor-换行' } } },
            { label: 'PRINTFORMW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-跟随SetColor-换行后等待' } } },
            { label: 'PRINTFORMK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-跟随ForceKana' } } },
            { label: 'PRINTFORMKL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-跟随ForceKana-换行' } } },
            { label: 'PRINTFORMKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTFORMD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-忽略SetColor' } } },
            { label: 'PRINTFORMDL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-忽略SetColor-换行' } } },
            { label: 'PRINTFORMDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-忽略SetColor-换行后等待' } } },
            { label: 'PRINTFORMLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-左对齐-跟随SetColor' } } },
            { label: 'PRINTFORMLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTFORMLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-左对齐-跟随ForceKana' } } },
            { label: 'PRINTFORMLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTFORMLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-左对齐-忽略SetColor' } } },
            { label: 'PRINTFORMLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTFORMC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-右对齐-跟随SetColor' } } },
            { label: 'PRINTFORMCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTFORMCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-右对齐-跟随ForceKana' } } },
            { label: 'PRINTFORMCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTFORMCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-右对齐-忽略SetColor' } } },
            { label: 'PRINTFORMCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTFORMS', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-跟随SetColor' } } },
            { label: 'PRINTFORMSL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-跟随SetColor-换行' } } },
            { label: 'PRINTFORMSW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-跟随SetColor-换行后等待' } } },
            { label: 'PRINTFORMSK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-跟随ForceKana' } } },
            { label: 'PRINTFORMSKL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-跟随ForceKana-换行' } } },
            { label: 'PRINTFORMSKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTFORMSD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-忽略SetColor' } } },
            { label: 'PRINTFORMSDL', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-忽略SetColor-换行' } } },
            { label: 'PRINTFORMSDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-忽略SetColor-换行后等待' } } },
            { label: 'PRINTFORMSLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-左对齐-跟随SetColor' } } },
            { label: 'PRINTFORMSLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTFORMSLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-左对齐-跟随ForceKana' } } },
            { label: 'PRINTFORMSLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTFORMSLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-左对齐-忽略SetColor' } } },
            { label: 'PRINTFORMSLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTFORMSC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-右对齐-跟随SetColor' } } },
            { label: 'PRINTFORMSCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTFORMSCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-右对齐-跟随ForceKana' } } },
            { label: 'PRINTFORMSCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTFORMSCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-右对齐-忽略SetColor' } } },
            { label: 'PRINTFORMSCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后自动换行-格式化字符串表达式-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLE', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-跟随SetColor' } } },
            { label: 'PRINTSINGLEW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-跟随ForceKana' } } },
            { label: 'PRINTSINGLEKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLED', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-忽略SetColor' } } },
            { label: 'PRINTSINGLEDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLELC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-左对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLELCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLELCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-左对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLELCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLELCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-左对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLELCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-右对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLECW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLECK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-右对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLECKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLECD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-右对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLECDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEV', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-跟随SetColor' } } },
            { label: 'PRINTSINGLEVW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEVK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-跟随ForceKana' } } },
            { label: 'PRINTSINGLEVKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEVD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-忽略SetColor' } } },
            { label: 'PRINTSINGLEVDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEVLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-左对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLEVLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEVLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-左对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLEVLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEVLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-左对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLEVLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEVC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-右对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLEVCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEVCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-右对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLEVCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEVCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-右对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLEVCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-数值表达式-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLES', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-跟随SetColor' } } },
            { label: 'PRINTSINGLESW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLESK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-跟随ForceKana' } } },
            { label: 'PRINTSINGLESKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLESD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-忽略SetColor' } } },
            { label: 'PRINTSINGLESDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLESLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-左对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLESLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLESLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-左对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLESLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLESLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-左对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLESLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLESC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-右对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLESCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLESCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-右对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLESCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLESCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-右对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLESCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-字符串表达式-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORM', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-跟随SetColor' } } },
            { label: 'PRINTSINGLEFORMW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-跟随ForceKana' } } },
            { label: 'PRINTSINGLEFORMKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEFORMD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-忽略SetColor' } } },
            { label: 'PRINTSINGLEFORMDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-左对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLEFORMLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-左对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLEFORMLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEFORMLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-左对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLEFORMLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-右对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLEFORMCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-右对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLEFORMCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEFORMCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-右对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLEFORMCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串-右对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMS', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-跟随SetColor' } } },
            { label: 'PRINTSINGLEFORMSW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-跟随ForceKana' } } },
            { label: 'PRINTSINGLEFORMSKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-忽略SetColor' } } },
            { label: 'PRINTSINGLEFORMSDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSLC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-左对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLEFORMSLCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-左对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSLCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-左对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLEFORMSLCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-左对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSLCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-左对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLEFORMSLCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-左对齐-忽略SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSC', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-右对齐-跟随SetColor' } } },
            { label: 'PRINTSINGLEFORMSCW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-右对齐-跟随SetColor-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSCK', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-右对齐-跟随ForceKana' } } },
            { label: 'PRINTSINGLEFORMSCKW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-右对齐-跟随ForceKana-换行后等待' } } },
            { label: 'PRINTSINGLEFORMSCD', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-右对齐-忽略SetColor' } } },
            { label: 'PRINTSINGLEFORMSCDW', detail: { 'zh-CN': { short: '输出', long: '输出-溢出后不换行-格式化字符串表达式-右对齐-忽略SetColor-换行后等待' } } }
        
        ]
    }
}